site_name: Network Pro Strategies
site_url: https://netwk.pro/docs/
repo_url: https://github.com/netwk-pro/netwk-pro-blog
repo_name: GitHub
docs_dir: docs_raw
site_dir: dist/docs

theme:
  name: material
  language: en
  font: false
  logo: img/logo.png
  favicon: img/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: amber
      accent: yellow
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    #- toc.integrate
    - navigation.top
    - search.suggest

extra:
  base_url: /docs/
  consent:
    title: Cookie Consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
      github:
        name: GitHub
        checked: true
    actions:
      - reject
      - accept
      - manage
  social:
    - icon: fontawesome/brands/instagram
      name: Network Pro on Instagram
      link: https://instagram.com/netwk_pro/
    - icon: fontawesome/brands/facebook
      name: Network Pro on Facebook
      link: https://facebook.com/neteng.pro/
    - icon: fontawesome/brands/linkedin
      name: Network Pro on LinkedIn
      link: https://linkedin.com/company/netwk-pro/
    - icon: fontawesome/brands/mastodon
      name: Network Pro on Mastoon
      link: https://noc.social/@neteng_pro/
    - icon: fontawesome/solid/at
      name: Contact Us
      link: https://contact.neteng.pro/

copyright: >
  Copyright &copy; 2025 Network Pro Strategies (Network Pro&trade;) –
  <a href="#__consent">Change cookie settings</a>

plugins:
  - privacy
  - search
  - meta
  - blog:
      #blog_toc: true
      archive_date_format: MMMM yyyy
  - tags:
      tags_file: tags.md
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

nav:
  - About Us: README.md
  - Blog:
      - blog/index.md
  - Legal Documentation:
      - legal.md
      - privacy.md
      - terms-use.md
      - terms-conditions.md
  - Contributing:
      - conduct.md
  - Tags:
      - tags.md
  - Back to Website: https://netwk.pro/
