# Copyright © 2025 Network Pro Strategies (Network Pro™)
# SPDX-License-Identifier: CC-BY-4.0 OR GPL-3.0-or-later
# This file is part of Network Pro

name: 🐛 Bug Report
description: 'File a report to help us improve.'
title: '[Bug]: '
labels: ['bug', 'needs triage']
assignees: SunDevil311

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report! Please complete all required fields below.

  - type: input
    id: contact
    attributes:
      label: 'Contact Details'
      description: 'How can we get in touch with you if we need more information?'
      placeholder: 'your@email.com'
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: 'What happened?'
      description: 'Describe the bug. What did you expect to happen?'
      placeholder: 'Tell us what you see!'
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 'Steps to Reproduce'
      description: 'List clear steps to reproduce the issue.'
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 'Environment'
      description: 'What platform, OS, browser, or version are you using?'
      placeholder: 'e.g. macOS 14, Chrome 125, iOS 17.5'
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: 'Prerequisites'
      description: 'Please confirm the following before submitting:'
      options:
        - label: 'I have searched for [duplicate or closed issues](https://github.com/netwk-pro/netwk-pro.github.io/issues)'
          required: true
        - label: 'I have read the [contributing guidelines](https://github.com/netwk-pro/.github/blob/master/.github/CONTRIBUTING.md)'
          required: true

  - type: textarea
    id: additional
    attributes:
      label: 'Additional Information'
      description: 'Add any other context, screenshots, or system logs here.'
      placeholder: 'Anything else we should know?'
    validations:
      required: false
