# .github/workflows/validate-lockfile.yml
#
# Copyright © 2025-2026 Network Pro Strategies (Network Pro™)
# SPDX-License-Identifier: CC-BY-4.0 OR GPL-3.0-or-later
# This file is part of Network Pro

name: Validate lockfile

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  lockfile:
    runs-on: ubuntu-24.04
    env:
      ENV_MODE: ci

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Upgrade npm
        run: npm install -g npm@11.17.0

      - name: Check lockfile
        run: npm ci --ignore-scripts --dry-run
